### ISSUE TITLE
request fix problem ssl

### ISSUE THREAD

**Issue by samirios1** [hola/player#19]
https://hola.org/play#v=http%3A%2F%2Fdistribution.bbb3d.renderfarming.net%2Fvideo%2Fmp4%2Fbbb_sunflower_1080p_30fps_normal.mp4.torrent

I use the SSL certificate to prove their demos player but I have a problem when I can not play on that link

**Comment by xavico** [comment]
We think we have workaround for this issue. In the next couple of hours we will release it.
We will continue working on a permanent solution until the issue will be resolved.

**Comment by xavico** [comment]
The fixed was release. 
We will continue working on a permanent solution until the issue will be resolved.

**Comment by samirios1** [comment]
thanks!!

**Comment by samirios1** [comment]
s seriously? they will not fix the https will continue postponing until 2016 ?

**Comment by samirios1** [comment]
https

**Comment by xderry** [comment]
Videos on https pages should be possible today using the fallback we implemented: but not inside the same chrome/FF browser - rather it opens the hola-chromium browser (which acts as a fallback).
Does this fallback not work for you?

Why do we have this problem? because we serve the torrent to Chrome on localhost http://127.0.0.1:6853. We cannot serve it on https://127.0.0.1:6853 since you cannot get a signed certificate for localhost :-)
Browsers have protection against mixed secure/un-secure content - they do not allow them in the same page.

We are working now on some solution, but its complicated to implement, and we are not yet even sure if it will work.

If you have any suggestions for a solution, or would like to join our team to try and solve making it work we will be happy! Contact me at derry@hola.org

Derry

**Comment by xavico** [comment]
We think we solved this issue. In the next couple of hours we will release it.

**Comment by samirios1** [comment]
Thanks very very thanks!

**Comment by xavico** [comment]
The bug was fixed in version 1.10.291. It will take around 48 hours to update all the current users to the new version. 
If you still encounter this problem please reopen this issue.
