### ISSUE TITLE
Hola open firefox to play movies

### ISSUE THREAD

**Issue by datnguyencse** [hola/player#8]
This is make me really sad and going to leave your player, I really really hope you will bring it back like before. I spent two month to develop a website use your player, it nearly done and I really disappointed in this morning, I know that you want your product become popular, but please don't go the fast way, just let it simple and you will success. In the future, all of my user will download hola player from your website. The first time I found you, I'm realy happy and can't wait to replace ACE Stream to you, but now, I'm thinking again. Please!
Another way is I want use this:  
![screenshot_6](https://cloud.githubusercontent.com/assets/11866125/9288224/12c8cf92-4366-11e5-8cc0-6be0a1410b95.png)

but not a link, I want let user click on a image, a poster and then they see this popup.

**Comment by vladaaa1234** [comment]
I have the same problem, but I am worked on my site 8 month !

**Comment by xderry** [comment]
Its a bug. We are working on fixing it. Hope the fix will be out by Monday

**Comment by xavico** [comment]
We think we have this bug fixed. Please confirm whether it's solved or whether
you’re still having this issue.
- you can now force Hola to play MP4 in browser's <video> tag, without opening 
  Hola Firefox/VLC window: <div v="magnet:..." video_tag="1">
  Starting next week video_tag=0 will be the default, so if its important to you 
  to play in same window without opening Hola Firefox, please make sure to add 
  video_tag=1 in your HTML code already today.
- FYI: AVI/MKV/WMB/DIVX/XVID/...: Browsers do not support these formats, so 
  those are always opened in Hola Firefox/VLC browser.
- FYI: MP4: Browsers support <video> tags with MP4, but they sometimes dont 
  render correctly some videos. Hola Firefox/VLC browser always renders correctly, 
  since VLC is capable of handling correctly all MP4 encodings.
- FYI: There is a known bug that the Hola Firefox browser opens in the 
  background, not in the front. This will be fixed this week.
- FYI: Hola Firefox/VLC browser is going to be changed to Hola Chromium/VLC 
  based browser in the near weeks.
