### ISSUE TITLE
Hola open firefox to play movies

### ISSUE THREAD

**Issue by vladaaa1234** [hola/player#9]
What happened with Hola player, why dont work ?

**Comment by xderry** [comment]
Is the problem only in Chrome, or also in Firefox?

**Comment by datnguyencse** [comment]
It will be repaired within two, three... day, they promised, stay calm.

**Comment by datnguyencse** [comment]
Dear xderry, only on chrome , firefox working fine.

**Comment by xavico** [comment]
We think we have this bug fixed. Please confirm whether it's solved or whether
you’re still having this issue.
- you can now force Hola to play MP4 in browser's <video> tag, without opening 
  Hola Firefox/VLC window: <div v="magnet:..." video_tag="1">
  Starting next week video_tag=0 will be the default, so if its important to you 
  to play in same window without opening Hola Firefox, please make sure to add 
  video_tag=1 in your HTML code already today.
- FYI: AVI/MKV/WMB/DIVX/XVID/...: Browsers do not support these formats, so 
  those are always opened in Hola Firefox/VLC browser.
- FYI: MP4: Browsers support <video> tags with MP4, but they sometimes dont 
  render correctly some videos. Hola Firefox/VLC browser always renders correctly, 
  since VLC is capable of handling correctly all MP4 encodings.
- FYI: There is a known bug that the Hola Firefox browser opens in the 
  background, not in the front. This will be fixed this week.
- FYI: Hola Firefox/VLC browser is going to be changed to Hola Chromium/VLC 
  based browser in the near weeks.

**Comment by datnguyencse** [comment]
Thank you so much, it fixed now.
